version: '3.8'

services:
   phplist:
     container_name: phplist-alpine
     image: phplist-alpine:3.6.14
     volumes:
       - ${IMAGES:-images}:/var/www/phpList3/public_html/images
       - ${PLUGINS:-plugins}:/var/www/phpList3/public_html/lists/admin/plugins
     ports:
       - "${PORT:-8000}:80"
     restart: unless-stopped
     environment:
       DB_HOST: ${MYSQL_HOST}
       DB_USER: ${MYSQL_USER}
       DB_PASSWORD: ${MYSQL_PASSWORD}
       DB_NAME: ${MYSQL_DATABASE}
       ADMIN_NAME: ${PHPLIST_ADMINNAME}
       ADMIN_PASSWORD: ${PHPLIST_ADMINPASSWORD}
       ADMIN_EMAIL: ${PHPLIST_ADMINEMAIL}
       HOSTNAME: ${HOSTNAME}
       PORT: ${PORT}
       MAILHOST: ${MAILHOST}
       PHPLISTINIT: ${INITIALISE_PHPLIST:-1}
       APIACCESS: ${API_ACCESS_ENABLED:-0}
       ALLOW_ATTACHMENTS: ${ALLOW_ATTACHMENTS:-0}
       bounce_mailbox_host: ${bounce_mailbox_host}
       bounce_mailbox_user: ${bounce_mailbox_user}
       bounce_mailbox_password: ${bounce_mailbox_password}
       bounce_mailbox_port: ${bounce_mailbox_port}
       bounce_mailbox_purge: ${bounce_mailbox_purge}
       bounce_mailbox_purge_unprocessed: ${bounce_mailbox_purge_unprocessed}
       bounce_unsubscribe_threshold: ${bounce_unsubscribe_threshold}

volumes:
    images:
    plugins: